<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title><?= $this->title ?> | <?= $this->projectName ?></title>
	<base href="<?= $this->baseHref ?>"/>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">
	<?= $this->implodeCSS() ?>
</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser
	today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better
	experience this site.</p>
<![endif]-->

<!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="."><?= $this->projectName ?></a>
		</div>
		<div class="collapse navbar-collapse">

			<?= $this->menu ?>

			<?= $this->loginForm ?>
		</div>
	</div>
</div>

<div class="container">

	<!-- Example row of columns -->
	<div class="row">
		<div class="col-md-2 sidebar">
			<?= $this->sidebar ?>
		</div>
		<?= $this->content ?>
	</div>

	<hr>

	<footer>
		<p>&copy; <?= date('Y') ?> Slawa</p>
	</footer>

</div> <!-- /container -->

<?= $this->implodeJS() ?>

</body>
</html>
